version: "3"
services:
  php:
    build: .docker/php
    container_name: "php-srv"
    image: server-php-nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: "nginx-srv"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "80:80"
    restart: always
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: "postgres-srv"
    ports:
      - "5432:5432"
    volumes:
      - .docker/db:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/initial_data.sql:/docker-entrypoint-initdb.d/initial_data.sql
    environment:
      POSTGRES_PASSWORD: "docker"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge